const patients = [
  {
    id: 1,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
  {
    id: 2,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
  {
    id: 3,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
  {
    id: 4,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
  {
    id: 5,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
  {
    id: 6,
    name: 'Logan Paul',
    address: '4307 Hilltop Haven Drive, Newark NJ',
    phoneNumber: '123-456-7890',
    email: 'loganpaul@gmail.com',
    reasonForVisit: 'Torn ACL',
    age: '31',
    injuryId: 3,
    insurance: 'Fidelis',
  },
];

export default patients;
