import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className='text-blue-500'>
          <div>
            <Link href='/'>LOGO</Link>
          </div>
          <div>
            <Link href='/'>About Us</Link>
            <Link href='/'>Services</Link>
            <Link href='/'>Log In</Link>
            <button>Get Started</button>
          </div>
        </main>
        {children}
      </body>
    </html>
  );
}
